version: "1.0"
info:
  model: int-scaffold
packages:
- name: Projectnonadmin1205Project
  gitServerName: srcCtrl_Github_nonadmin_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
