version: "1.0"
info:
  model: int-scaffold
packages:
- name: Projectnonadmin1205Project
  gitServerName: srcCtrl_Github_nonadmin_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.projectnonadmin1205.integrations:gg
  packages:
  - name: Projectnonadmin1205Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
